apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://noroff-loki:3100
    isDefault: false
